report(currency): Update support policy.
Update the Tracer support policy to 45 days instead of 30 days.

Fixed typos.

Signed-off-by: Paulo Vital <paulo.vital@ibm.com>

diff --git a/.tekton/.currency/currency-tasks.yaml b/.tekton/.currency/currency-tasks.yaml
--- a/.tekton/.currency/currency-tasks.yaml
+++ b/.tekton/.currency/currency-tasks.yaml
@@ -44,7 +44,7 @@ spec:
 
         python scripts/generate_report.py
         if [ $? -ne 0 ]; then
-            echo "Error occured while generating the ruby tracer currency report." >&2
+            echo "Error occurred while generating the ruby tracer currency report." >&2
             exit 1
         fi
         cat docs/report.md
@@ -90,5 +90,5 @@ spec:
         
         git add .
         
-        git commit -m "chore: Updated ruby currency report"
+        git commit -m "chore: Updated Ruby currency report"
         git push origin main
